name: ci

on:
  push:
    branches:
      - "**"
    tags:
      - "*"
  pull_request:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        base_image: [ "alpine3.20", "alpine3.19", "bookworm" ,"bullseye" ,"slim-bookworm"  ,"slim-bullseye" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            koxudaxi/python
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=3.14.0a0-${{ matrix.base_image }}
            type=raw,value=3.14.0a0-tag-strings-rebased-${{ matrix.base_image }}
            type=raw,value=3.14.0a0-tag-strings-rebased-62c9e0a-${{ matrix.base_image }}
            type=sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker/${{ matrix.base_image }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
